function label = autoLabel(p)
%AUTOLABEL Build a descriptive slug for exports based on key parameters.
%
%   label = AUTOLABEL(p) constructs a lowercase identifier composed of
%   selected parameter values that is suitable for filenames.

    tokens = [ ...
        "urchin"; ...
        "core" + valueToken(p.CoreRadius); ...
        "len" + valueToken(p.SpikeLength); ...
        "count" + valueToken(p.SpikeCount); ...
        "tip" + valueToken(p.SpikeTipDiameter); ...
        "conicity" + valueToken(p.SpikeConicality); ...
        "fluc" + valueToken(p.FlucFactor); ...
        "dist" + valueToken(p.DistMethod); ...
        "flucMethod" + valueToken(p.FlucMethod) ...
    ];
    label = lower(join(tokens, "_"));
    label = regexprep(label, '[_]+', '_');
    label = regexprep(label, '[^a-z0-9_]', '');
    label = char(label);
end
