function label = autoLabel(p)
%AUTOLABEL Build a descriptive slug for exports based on key parameters.
%
%   label = AUTOLABEL(p) constructs a lowercase identifier composed of
%   selected parameter values that is suitable for filenames.

    tokens = [ ...
        "urchin"; ...
        "core" + valueToken(p.rCore); ...
        "len" + valueToken(p.spikeLength); ...
        "count" + valueToken(p.spikeCount); ...
        "tip" + valueToken(p.spikeTip); ...
        "conicity" + valueToken(p.spikeConicality); ...
        "fluc" + valueToken(p.flucFactor); ...
        "dist" + valueToken(p.distMethod); ...
        "flucMethod" + valueToken(p.flucMethod) ...
    ];
    label = lower(join(tokens, "_"));
    label = regexprep(label, '[_]+', '_');
    label = regexprep(label, '[^a-z0-9_]', '');
    label = char(label);
end
